---
- name: Check instance app_{{ item.seq_num }}
  ec2_instance_info:
    filters:
      "tag:Name": app_{{ item.seq_num }}
      instance-state-name: [ "running" ]
  register: ec2_info

# the user_data cos in my case i don't have a VPN or something like this
- name: Provision
  block:
  
  - name: Provision instance app_{{ item.seq_num }}
    ec2:
        image: "{{ AMI.image_id }}"
        instance_type: t2.micro
        region: "{{ region }}"
        key_name: "{{ nginx_ssh_key }}"
        group_id: "{{ result_sec_group.group_id }}"
        vpc_subnet_id: "{{ item.subnet }}"
        wait: true
        user_data: |
          #!/bin/bash 
          sudo yum update -y && 
          sudo amazon-linux-extras install nginx1.12 -y && 
          sudo bash -c 'cat << EOF > /usr/share/nginx/html/index.html
          <!DOCTYPE html>
          <html><body>
          <h1>Hello from app_{{ item.seq_num }}
          </body></html>
          EOF'
          sudo service nginx start && 
          sudo chkconfig nginx on
        instance_tags:
          Name: "app_{{ item.seq_num }}"
  
  - name: Check instance app_{{ item.seq_num }}
    ec2_instance_info:
      filters:
        "tag:Name": app_{{ item.seq_num }}
        instance-state-name: [ "running" ]
    register: ec2

  - name: Get VPC subnet info
    ec2_vpc_subnet_info:
      subnet_ids: "{{ ec2.instances[0].subnet_id }}"
    register: subnet_info

  - name: Append to nginx conf
    set_fact: 
      nginx_conf_dict: "{{ nginx_conf_dict | combine ( { subnet_info.subnets[0].availability_zone : nginx_conf_dict[subnet_info.subnets[0].availability_zone] | union([ ec2.instances[0].private_dns_name ]) } ) }}" 
  
  when: ec2_info.instances | length == 0 or ec2_info.instances[0].state.name == "terminated"


